[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = ["curl", "gnupg", "apt-transport-https"]

# Install ODBC Driver 17 for SQL Server
[phases.setup]
cmds = [
    "curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg",
    "curl https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list",
    "apt-get update",
    "ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"
